version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - letalk-app
  api-server:
    image: api-server
    ports:
      - "3333:3333"
    networks:
      - letalk-app
    depends_on:
      - database
  database:
    image: postgres
    ports: 
      - 5432:5432
    networks:
      - letalk-app
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=letalk
    volumes:
      - pgdata:/data/postgres
networks:
  letalk-app:
    driver: bridge
volumes:
  pgdata:
    driver: local