version: "3"
services:
  react-app:
    container_name: client-container
    build: ./frontend
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - api-server
  api-server:
    container_name: api-container
    build: ./backend
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - database
  database:
    container_name: postgres-backend
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=letalk
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
